import React from 'react';
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Layout = ({children, title}) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <header className="bg-red-700 py-10 mb-10">
                <Link href="/">
                    <a>
                        <h1 className="text-6xl text-center text-amber-400">{title}</h1>
                    </a>
                </Link>
            </header>

            <main className="container mx-auto">
                {children}
            </main>

            <footer className="flex justify-center items-center mt-10">
                <a
                    className="flex flex-col"
                    href="http://zxhirali.ca/"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Built by{''}
                    <Image src="/zxhir.png" alt="Logo" width={72} height={72}/>
                </a>
            </footer>
        </div>
    );
};

export default Layout;
